<?php
// Généré à partir de https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Items par BIWikiCfgPageParser

$export = array (
  0 => 
  array (
    'class' => 'ItemWatch',
    'name' => 'Watch',
    'description' => 'Useful for recognizing clock position.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_Soldier_F',
      1 => 'B_Soldier_02_f',
      2 => 'B_Soldier_03_f',
      3 => 'B_Soldier_04_f',
      4 => 'B_Soldier_05_f',
      5 => 'B_Soldier_lite_F',
      6 => 'B_Soldier_GL_F',
      7 => 'B_soldier_AR_F',
      8 => 'B_Soldier_SL_F',
      9 => 'B_Soldier_TL_F',
      10 => 'B_soldier_M_F',
      11 => 'B_soldier_LAT_F',
      12 => 'B_medic_F',
      13 => 'B_soldier_repair_F',
      14 => 'B_soldier_exp_F',
      15 => 'B_Helipilot_F',
      16 => 'B_diver_F',
      17 => 'B_diver_TL_F',
      18 => 'B_diver_exp_F',
      19 => 'B_spotter_F',
      20 => 'B_sniper_F',
      21 => 'B_RangeMaster_F',
      22 => 'C_man_1',
      23 => 'C_man_1_1_F',
      24 => 'C_man_1_2_F',
      25 => 'C_man_1_3_F',
      26 => 'C_man_polo_1_F',
      27 => 'C_man_polo_2_F',
      28 => 'C_man_polo_3_F',
      29 => 'C_man_polo_4_F',
      30 => 'C_man_polo_5_F',
      31 => 'C_man_polo_6_F',
      32 => 'C_Orestes',
      33 => 'C_Nikos',
      34 => 'O_Soldier_F',
      35 => 'O_officer_F',
      36 => 'O_Soldier_02_F',
      37 => 'O_Soldier_lite_F',
      38 => 'O_Soldier_GL_F',
      39 => 'O_Soldier_AR_F',
      40 => 'O_Soldier_SL_F',
      41 => 'O_Soldier_TL_F',
      42 => 'O_soldier_M_F',
      43 => 'O_Soldier_LAT_F',
      44 => 'O_medic_F',
      45 => 'O_soldier_repair_F',
      46 => 'O_soldier_exp_F',
      47 => 'O_helipilot_F',
      48 => 'O_diver_F',
      49 => 'O_diver_TL_F',
      50 => 'O_diver_exp_F',
      51 => 'O_spotter_F',
      52 => 'O_sniper_F',
      53 => 'B_Soldier_A_F',
      54 => 'B_soldier_AT_F',
      55 => 'B_soldier_AA_F',
      56 => 'B_engineer_F',
      57 => 'B_crew_F',
      58 => 'B_officer_F',
      59 => 'B_Competitor_F',
      60 => 'B_recon_F',
      61 => 'B_recon_LAT_F',
      62 => 'B_recon_exp_F',
      63 => 'B_recon_medic_F',
      64 => 'B_recon_TL_F',
      65 => 'B_recon_M_F',
      66 => 'B_recon_JTAC_F',
      67 => 'B_soldier_AAR_F',
      68 => 'B_soldier_AAT_F',
      69 => 'B_soldier_AAA_F',
      70 => 'O_Soldier_A_F',
      71 => 'O_Soldier_AT_F',
      72 => 'O_Soldier_AA_F',
      73 => 'O_engineer_F',
      74 => 'O_crew_F',
      75 => 'O_recon_F',
      76 => 'O_recon_M_F',
      77 => 'O_recon_LAT_F',
      78 => 'O_recon_medic_F',
      79 => 'O_recon_exp_F',
      80 => 'O_recon_JTAC_F',
      81 => 'O_recon_TL_F',
      82 => 'O_Soldier_AAR_F',
      83 => 'O_Soldier_AAT_F',
      84 => 'O_Soldier_AAA_F',
      85 => 'I_Soldier_02_F',
      86 => 'I_Soldier_03_F',
      87 => 'I_Soldier_04_F',
      88 => 'I_soldier_F',
      89 => 'I_Soldier_lite_F',
      90 => 'I_Soldier_A_F',
      91 => 'I_Soldier_GL_F',
      92 => 'I_Soldier_AR_F',
      93 => 'I_Soldier_SL_F',
      94 => 'I_Soldier_TL_F',
      95 => 'I_Soldier_M_F',
      96 => 'I_Soldier_LAT_F',
      97 => 'I_Soldier_AT_F',
      98 => 'I_Soldier_AA_F',
      99 => 'I_medic_F',
      100 => 'I_Soldier_repair_F',
      101 => 'I_Soldier_exp_F',
      102 => 'I_engineer_F',
      103 => 'I_crew_F',
      104 => 'I_helipilot_F',
      105 => 'I_helicrew_F',
      106 => 'I_officer_F',
      107 => 'I_Spotter_F',
      108 => 'I_Sniper_F',
      109 => 'I_diver_F',
      110 => 'I_diver_exp_F',
      111 => 'I_diver_TL_F',
      112 => 'I_Soldier_AAR_F',
      113 => 'I_Soldier_AAT_F',
      114 => 'I_Soldier_AAA_F',
      115 => 'B_Pilot_F',
      116 => 'B_helicrew_F',
      117 => 'B_soldier_PG_F',
      118 => 'B_Story_SF_Captain_F',
      119 => 'B_Story_Protagonist_F',
      120 => 'B_Story_Engineer_F',
      121 => 'B_Story_Colonel_F',
      122 => 'B_Story_Pilot_F',
      123 => 'B_Story_Tank_Commander_F',
      124 => 'B_support_MG_F',
      125 => 'B_support_GMG_F',
      126 => 'B_support_Mort_F',
      127 => 'B_support_AMG_F',
      128 => 'B_support_AMort_F',
      129 => 'I_pilot_F',
      130 => 'I_Story_Colonel_F',
      131 => 'I_support_MG_F',
      132 => 'I_support_GMG_F',
      133 => 'I_support_Mort_F',
      134 => 'I_support_AMG_F',
      135 => 'I_support_AMort_F',
      136 => 'O_Pilot_F',
      137 => 'O_helicrew_F',
      138 => 'O_soldier_PG_F',
      139 => 'O_Story_Colonel_F',
      140 => 'O_Story_CEO_F',
      141 => 'O_support_MG_F',
      142 => 'O_support_GMG_F',
      143 => 'O_support_Mort_F',
      144 => 'O_support_AMG_F',
      145 => 'O_support_AMort_F',
      146 => 'O_soldierU_F',
      147 => 'O_soldierU_AR_F',
      148 => 'O_soldierU_AAR_F',
      149 => 'O_soldierU_LAT_F',
      150 => 'O_soldierU_AT_F',
      151 => 'O_soldierU_AAT_F',
      152 => 'O_soldierU_AA_F',
      153 => 'O_soldierU_AAA_F',
      154 => 'O_soldierU_TL_F',
      155 => 'O_SoldierU_SL_F',
      156 => 'O_soldierU_medic_F',
      157 => 'O_soldierU_repair_F',
      158 => 'O_soldierU_exp_F',
      159 => 'O_engineer_U_F',
      160 => 'O_soldierU_M_F',
      161 => 'O_soldierU_A_F',
      162 => 'O_SoldierU_GL_F',
      163 => 'C_man_p_fugitive_F',
      164 => 'C_man_p_fugitive_F_afro',
      165 => 'C_man_p_fugitive_F_euro',
      166 => 'C_man_p_fugitive_F_asia',
      167 => 'C_man_p_beggar_F',
      168 => 'C_man_p_beggar_F_afro',
      169 => 'C_man_p_beggar_F_euro',
      170 => 'C_man_p_beggar_F_asia',
      171 => 'C_man_w_worker_F',
      172 => 'C_man_hunter_1_F',
      173 => 'C_man_p_shorts_1_F',
      174 => 'C_man_p_shorts_1_F_afro',
      175 => 'C_man_p_shorts_1_F_euro',
      176 => 'C_man_p_shorts_1_F_asia',
      177 => 'C_man_shorts_1_F',
      178 => 'C_man_shorts_1_F_afro',
      179 => 'C_man_shorts_1_F_euro',
      180 => 'C_man_shorts_1_F_asia',
      181 => 'C_man_shorts_2_F',
      182 => 'C_man_shorts_2_F_afro',
      183 => 'C_man_shorts_2_F_euro',
      184 => 'C_man_shorts_2_F_asia',
      185 => 'C_man_shorts_3_F',
      186 => 'C_man_shorts_3_F_afro',
      187 => 'C_man_shorts_3_F_euro',
      188 => 'C_man_shorts_3_F_asia',
      189 => 'C_man_shorts_4_F',
      190 => 'C_man_shorts_4_F_afro',
      191 => 'C_man_shorts_4_F_euro',
      192 => 'C_man_shorts_4_F_asia',
      193 => 'C_man_pilot_F',
      194 => 'C_man_polo_1_F_afro',
      195 => 'C_man_polo_1_F_euro',
      196 => 'C_man_polo_1_F_asia',
      197 => 'C_man_polo_2_F_afro',
      198 => 'C_man_polo_2_F_euro',
      199 => 'C_man_polo_2_F_asia',
      200 => 'C_man_polo_3_F_afro',
      201 => 'C_man_polo_3_F_euro',
      202 => 'C_man_polo_3_F_asia',
      203 => 'C_man_polo_4_F_afro',
      204 => 'C_man_polo_4_F_euro',
      205 => 'C_man_polo_4_F_asia',
      206 => 'C_man_polo_5_F_afro',
      207 => 'C_man_polo_5_F_euro',
      208 => 'C_man_polo_5_F_asia',
      209 => 'C_man_polo_6_F_afro',
      210 => 'C_man_polo_6_F_euro',
      211 => 'C_man_polo_6_F_asia',
      212 => 'I_G_Soldier_F',
      213 => 'I_G_Soldier_lite_F',
      214 => 'I_G_Soldier_SL_F',
      215 => 'I_G_Soldier_TL_F',
      216 => 'I_G_Soldier_AR_F',
      217 => 'I_G_medic_F',
      218 => 'I_G_engineer_F',
      219 => 'I_G_Soldier_exp_F',
      220 => 'I_G_Soldier_GL_F',
      221 => 'I_G_Soldier_M_F',
      222 => 'I_G_Soldier_LAT_F',
      223 => 'I_G_Soldier_A_F',
      224 => 'I_G_officer_F',
      225 => 'B_G_Soldier_F',
      226 => 'O_G_Soldier_F',
      227 => 'B_G_Soldier_lite_F',
      228 => 'O_G_Soldier_lite_F',
      229 => 'B_G_Soldier_SL_F',
      230 => 'O_G_Soldier_SL_F',
      231 => 'B_G_Soldier_TL_F',
      232 => 'O_G_Soldier_TL_F',
      233 => 'B_G_Soldier_AR_F',
      234 => 'O_G_Soldier_AR_F',
      235 => 'B_G_medic_F',
      236 => 'O_G_medic_F',
      237 => 'B_G_engineer_F',
      238 => 'O_G_engineer_F',
      239 => 'B_G_Soldier_exp_F',
      240 => 'O_G_Soldier_exp_F',
      241 => 'B_G_Soldier_GL_F',
      242 => 'O_G_Soldier_GL_F',
      243 => 'B_G_Soldier_M_F',
      244 => 'O_G_Soldier_M_F',
      245 => 'B_G_Soldier_LAT_F',
      246 => 'O_G_Soldier_LAT_F',
      247 => 'B_G_Soldier_A_F',
      248 => 'O_G_Soldier_A_F',
      249 => 'B_G_officer_F',
      250 => 'O_G_officer_F',
      251 => 'I_G_Story_Protagonist_F',
      252 => 'B_soldier_UAV_F',
      253 => 'I_soldier_UAV_F',
      254 => 'O_soldier_UAV_F',
      255 => 'B_UAV_AI',
      256 => 'O_UAV_AI',
      257 => 'I_UAV_AI',
      258 => 'Underwear_F',
      259 => 'b_soldier_survival_F',
      260 => 'B_CTRG_soldier_GL_LAT_F',
      261 => 'B_CTRG_soldier_engineer_exp_F',
      262 => 'B_CTRG_soldier_M_medic_F',
      263 => 'B_CTRG_soldier_AR_A_F',
      264 => 'I_G_Story_SF_Captain_F',
      265 => 'I_G_resistanceLeader_F',
      266 => 'I_G_resistanceCommander_F',
      267 => 'C_Nikos_aged',
      268 => 'C_journalist_F',
      269 => 'C_scientist_F',
      270 => 'b_soldier_unarmed_f',
      271 => 'b_g_soldier_unarmed_f',
      272 => 'o_soldier_unarmed_f',
      273 => 'o_g_soldier_unarmed_f',
      274 => 'i_soldier_unarmed_f',
      275 => 'i_g_soldier_unarmed_f',
      276 => 'VirtualMan_F',
      277 => 'VirtualCurator_F',
      278 => 'B_VirtualCurator_F',
      279 => 'O_VirtualCurator_F',
      280 => 'I_VirtualCurator_F',
      281 => 'C_VirtualCurator_F',
    ),
  ),
  1 => 
  array (
    'class' => 'ItemCompass',
    'name' => 'Compass',
    'description' => 'Useful for navigation.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_Soldier_F',
      1 => 'B_Soldier_02_f',
      2 => 'B_Soldier_03_f',
      3 => 'B_Soldier_04_f',
      4 => 'B_Soldier_05_f',
      5 => 'B_Soldier_lite_F',
      6 => 'B_Soldier_GL_F',
      7 => 'B_soldier_AR_F',
      8 => 'B_Soldier_SL_F',
      9 => 'B_Soldier_TL_F',
      10 => 'B_soldier_M_F',
      11 => 'B_soldier_LAT_F',
      12 => 'B_medic_F',
      13 => 'B_soldier_repair_F',
      14 => 'B_soldier_exp_F',
      15 => 'B_Helipilot_F',
      16 => 'B_diver_F',
      17 => 'B_diver_TL_F',
      18 => 'B_diver_exp_F',
      19 => 'B_spotter_F',
      20 => 'B_sniper_F',
      21 => 'B_RangeMaster_F',
      22 => 'C_man_1',
      23 => 'C_man_1_1_F',
      24 => 'C_man_1_2_F',
      25 => 'C_man_1_3_F',
      26 => 'C_man_polo_1_F',
      27 => 'C_man_polo_2_F',
      28 => 'C_man_polo_3_F',
      29 => 'C_man_polo_4_F',
      30 => 'C_man_polo_5_F',
      31 => 'C_man_polo_6_F',
      32 => 'C_Orestes',
      33 => 'C_Nikos',
      34 => 'O_Soldier_F',
      35 => 'O_officer_F',
      36 => 'O_Soldier_02_F',
      37 => 'O_Soldier_lite_F',
      38 => 'O_Soldier_GL_F',
      39 => 'O_Soldier_AR_F',
      40 => 'O_Soldier_SL_F',
      41 => 'O_Soldier_TL_F',
      42 => 'O_soldier_M_F',
      43 => 'O_Soldier_LAT_F',
      44 => 'O_medic_F',
      45 => 'O_soldier_repair_F',
      46 => 'O_soldier_exp_F',
      47 => 'O_helipilot_F',
      48 => 'O_diver_F',
      49 => 'O_diver_TL_F',
      50 => 'O_diver_exp_F',
      51 => 'O_spotter_F',
      52 => 'O_sniper_F',
      53 => 'B_Soldier_A_F',
      54 => 'B_soldier_AT_F',
      55 => 'B_soldier_AA_F',
      56 => 'B_engineer_F',
      57 => 'B_crew_F',
      58 => 'B_officer_F',
      59 => 'B_Competitor_F',
      60 => 'B_recon_F',
      61 => 'B_recon_LAT_F',
      62 => 'B_recon_exp_F',
      63 => 'B_recon_medic_F',
      64 => 'B_recon_TL_F',
      65 => 'B_recon_M_F',
      66 => 'B_recon_JTAC_F',
      67 => 'B_soldier_AAR_F',
      68 => 'B_soldier_AAT_F',
      69 => 'B_soldier_AAA_F',
      70 => 'O_Soldier_A_F',
      71 => 'O_Soldier_AT_F',
      72 => 'O_Soldier_AA_F',
      73 => 'O_engineer_F',
      74 => 'O_crew_F',
      75 => 'O_recon_F',
      76 => 'O_recon_M_F',
      77 => 'O_recon_LAT_F',
      78 => 'O_recon_medic_F',
      79 => 'O_recon_exp_F',
      80 => 'O_recon_JTAC_F',
      81 => 'O_recon_TL_F',
      82 => 'O_Soldier_AAR_F',
      83 => 'O_Soldier_AAT_F',
      84 => 'O_Soldier_AAA_F',
      85 => 'I_Soldier_02_F',
      86 => 'I_Soldier_03_F',
      87 => 'I_Soldier_04_F',
      88 => 'I_soldier_F',
      89 => 'I_Soldier_lite_F',
      90 => 'I_Soldier_A_F',
      91 => 'I_Soldier_GL_F',
      92 => 'I_Soldier_AR_F',
      93 => 'I_Soldier_SL_F',
      94 => 'I_Soldier_TL_F',
      95 => 'I_Soldier_M_F',
      96 => 'I_Soldier_LAT_F',
      97 => 'I_Soldier_AT_F',
      98 => 'I_Soldier_AA_F',
      99 => 'I_medic_F',
      100 => 'I_Soldier_repair_F',
      101 => 'I_Soldier_exp_F',
      102 => 'I_engineer_F',
      103 => 'I_crew_F',
      104 => 'I_helipilot_F',
      105 => 'I_helicrew_F',
      106 => 'I_officer_F',
      107 => 'I_Spotter_F',
      108 => 'I_Sniper_F',
      109 => 'I_diver_F',
      110 => 'I_diver_exp_F',
      111 => 'I_diver_TL_F',
      112 => 'I_Soldier_AAR_F',
      113 => 'I_Soldier_AAT_F',
      114 => 'I_Soldier_AAA_F',
      115 => 'B_Pilot_F',
      116 => 'B_helicrew_F',
      117 => 'B_soldier_PG_F',
      118 => 'B_Story_SF_Captain_F',
      119 => 'B_Story_Protagonist_F',
      120 => 'B_Story_Engineer_F',
      121 => 'B_Story_Colonel_F',
      122 => 'B_Story_Pilot_F',
      123 => 'B_Story_Tank_Commander_F',
      124 => 'B_support_MG_F',
      125 => 'B_support_GMG_F',
      126 => 'B_support_Mort_F',
      127 => 'B_support_AMG_F',
      128 => 'B_support_AMort_F',
      129 => 'I_pilot_F',
      130 => 'I_Story_Colonel_F',
      131 => 'I_support_MG_F',
      132 => 'I_support_GMG_F',
      133 => 'I_support_Mort_F',
      134 => 'I_support_AMG_F',
      135 => 'I_support_AMort_F',
      136 => 'O_Pilot_F',
      137 => 'O_helicrew_F',
      138 => 'O_soldier_PG_F',
      139 => 'O_Story_Colonel_F',
      140 => 'O_Story_CEO_F',
      141 => 'O_support_MG_F',
      142 => 'O_support_GMG_F',
      143 => 'O_support_Mort_F',
      144 => 'O_support_AMG_F',
      145 => 'O_support_AMort_F',
      146 => 'O_soldierU_F',
      147 => 'O_soldierU_AR_F',
      148 => 'O_soldierU_AAR_F',
      149 => 'O_soldierU_LAT_F',
      150 => 'O_soldierU_AT_F',
      151 => 'O_soldierU_AAT_F',
      152 => 'O_soldierU_AA_F',
      153 => 'O_soldierU_AAA_F',
      154 => 'O_soldierU_TL_F',
      155 => 'O_SoldierU_SL_F',
      156 => 'O_soldierU_medic_F',
      157 => 'O_soldierU_repair_F',
      158 => 'O_soldierU_exp_F',
      159 => 'O_engineer_U_F',
      160 => 'O_soldierU_M_F',
      161 => 'O_soldierU_A_F',
      162 => 'O_SoldierU_GL_F',
      163 => 'C_man_p_fugitive_F',
      164 => 'C_man_p_fugitive_F_afro',
      165 => 'C_man_p_fugitive_F_euro',
      166 => 'C_man_p_fugitive_F_asia',
      167 => 'C_man_p_beggar_F',
      168 => 'C_man_p_beggar_F_afro',
      169 => 'C_man_p_beggar_F_euro',
      170 => 'C_man_p_beggar_F_asia',
      171 => 'C_man_w_worker_F',
      172 => 'C_man_hunter_1_F',
      173 => 'C_man_p_shorts_1_F',
      174 => 'C_man_p_shorts_1_F_afro',
      175 => 'C_man_p_shorts_1_F_euro',
      176 => 'C_man_p_shorts_1_F_asia',
      177 => 'C_man_shorts_1_F',
      178 => 'C_man_shorts_1_F_afro',
      179 => 'C_man_shorts_1_F_euro',
      180 => 'C_man_shorts_1_F_asia',
      181 => 'C_man_shorts_2_F',
      182 => 'C_man_shorts_2_F_afro',
      183 => 'C_man_shorts_2_F_euro',
      184 => 'C_man_shorts_2_F_asia',
      185 => 'C_man_shorts_3_F',
      186 => 'C_man_shorts_3_F_afro',
      187 => 'C_man_shorts_3_F_euro',
      188 => 'C_man_shorts_3_F_asia',
      189 => 'C_man_shorts_4_F',
      190 => 'C_man_shorts_4_F_afro',
      191 => 'C_man_shorts_4_F_euro',
      192 => 'C_man_shorts_4_F_asia',
      193 => 'C_man_pilot_F',
      194 => 'C_man_polo_1_F_afro',
      195 => 'C_man_polo_1_F_euro',
      196 => 'C_man_polo_1_F_asia',
      197 => 'C_man_polo_2_F_afro',
      198 => 'C_man_polo_2_F_euro',
      199 => 'C_man_polo_2_F_asia',
      200 => 'C_man_polo_3_F_afro',
      201 => 'C_man_polo_3_F_euro',
      202 => 'C_man_polo_3_F_asia',
      203 => 'C_man_polo_4_F_afro',
      204 => 'C_man_polo_4_F_euro',
      205 => 'C_man_polo_4_F_asia',
      206 => 'C_man_polo_5_F_afro',
      207 => 'C_man_polo_5_F_euro',
      208 => 'C_man_polo_5_F_asia',
      209 => 'C_man_polo_6_F_afro',
      210 => 'C_man_polo_6_F_euro',
      211 => 'C_man_polo_6_F_asia',
      212 => 'I_G_Soldier_F',
      213 => 'I_G_Soldier_lite_F',
      214 => 'I_G_Soldier_SL_F',
      215 => 'I_G_Soldier_TL_F',
      216 => 'I_G_Soldier_AR_F',
      217 => 'I_G_medic_F',
      218 => 'I_G_engineer_F',
      219 => 'I_G_Soldier_exp_F',
      220 => 'I_G_Soldier_GL_F',
      221 => 'I_G_Soldier_M_F',
      222 => 'I_G_Soldier_LAT_F',
      223 => 'I_G_Soldier_A_F',
      224 => 'I_G_officer_F',
      225 => 'B_G_Soldier_F',
      226 => 'O_G_Soldier_F',
      227 => 'B_G_Soldier_lite_F',
      228 => 'O_G_Soldier_lite_F',
      229 => 'B_G_Soldier_SL_F',
      230 => 'O_G_Soldier_SL_F',
      231 => 'B_G_Soldier_TL_F',
      232 => 'O_G_Soldier_TL_F',
      233 => 'B_G_Soldier_AR_F',
      234 => 'O_G_Soldier_AR_F',
      235 => 'B_G_medic_F',
      236 => 'O_G_medic_F',
      237 => 'B_G_engineer_F',
      238 => 'O_G_engineer_F',
      239 => 'B_G_Soldier_exp_F',
      240 => 'O_G_Soldier_exp_F',
      241 => 'B_G_Soldier_GL_F',
      242 => 'O_G_Soldier_GL_F',
      243 => 'B_G_Soldier_M_F',
      244 => 'O_G_Soldier_M_F',
      245 => 'B_G_Soldier_LAT_F',
      246 => 'O_G_Soldier_LAT_F',
      247 => 'B_G_Soldier_A_F',
      248 => 'O_G_Soldier_A_F',
      249 => 'B_G_officer_F',
      250 => 'O_G_officer_F',
      251 => 'I_G_Story_Protagonist_F',
      252 => 'B_soldier_UAV_F',
      253 => 'I_soldier_UAV_F',
      254 => 'O_soldier_UAV_F',
      255 => 'B_UAV_AI',
      256 => 'O_UAV_AI',
      257 => 'I_UAV_AI',
      258 => 'Underwear_F',
      259 => 'b_soldier_survival_F',
      260 => 'B_CTRG_soldier_GL_LAT_F',
      261 => 'B_CTRG_soldier_engineer_exp_F',
      262 => 'B_CTRG_soldier_M_medic_F',
      263 => 'B_CTRG_soldier_AR_A_F',
      264 => 'I_G_Story_SF_Captain_F',
      265 => 'I_G_resistanceLeader_F',
      266 => 'I_G_resistanceCommander_F',
      267 => 'C_Nikos_aged',
      268 => 'C_journalist_F',
      269 => 'C_scientist_F',
      270 => 'b_soldier_unarmed_f',
      271 => 'b_g_soldier_unarmed_f',
      272 => 'o_soldier_unarmed_f',
      273 => 'o_g_soldier_unarmed_f',
      274 => 'i_soldier_unarmed_f',
      275 => 'i_g_soldier_unarmed_f',
      276 => 'VirtualMan_F',
      277 => 'VirtualCurator_F',
      278 => 'B_VirtualCurator_F',
      279 => 'O_VirtualCurator_F',
      280 => 'I_VirtualCurator_F',
      281 => 'C_VirtualCurator_F',
    ),
  ),
  2 => 
  array (
    'class' => 'ItemGPS',
    'name' => 'GPS',
    'description' => 'Enables accurate positioning.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_Soldier_SL_F',
      1 => 'B_Soldier_TL_F',
      2 => 'B_diver_TL_F',
      3 => 'B_spotter_F',
      4 => 'B_sniper_F',
      5 => 'O_officer_F',
      6 => 'O_Soldier_SL_F',
      7 => 'O_Soldier_TL_F',
      8 => 'O_diver_TL_F',
      9 => 'O_spotter_F',
      10 => 'O_sniper_F',
      11 => 'B_officer_F',
      12 => 'B_recon_F',
      13 => 'B_recon_LAT_F',
      14 => 'B_recon_exp_F',
      15 => 'B_recon_medic_F',
      16 => 'B_recon_TL_F',
      17 => 'B_recon_M_F',
      18 => 'B_recon_JTAC_F',
      19 => 'O_recon_F',
      20 => 'O_recon_M_F',
      21 => 'O_recon_LAT_F',
      22 => 'O_recon_medic_F',
      23 => 'O_recon_exp_F',
      24 => 'O_recon_JTAC_F',
      25 => 'O_recon_TL_F',
      26 => 'I_Soldier_SL_F',
      27 => 'I_Soldier_TL_F',
      28 => 'I_officer_F',
      29 => 'I_Spotter_F',
      30 => 'I_Sniper_F',
      31 => 'I_diver_TL_F',
      32 => 'I_Story_Colonel_F',
      33 => 'O_soldierU_TL_F',
      34 => 'O_SoldierU_SL_F',
      35 => 'I_G_officer_F',
      36 => 'B_G_officer_F',
      37 => 'O_G_officer_F',
    ),
  ),
  3 => 
  array (
    'class' => 'ItemRadio',
    'name' => 'Radio',
    'description' => 'Enables communications.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_Soldier_F',
      1 => 'B_Soldier_02_f',
      2 => 'B_Soldier_03_f',
      3 => 'B_Soldier_04_f',
      4 => 'B_Soldier_05_f',
      5 => 'B_Soldier_lite_F',
      6 => 'B_Soldier_GL_F',
      7 => 'B_soldier_AR_F',
      8 => 'B_Soldier_SL_F',
      9 => 'B_Soldier_TL_F',
      10 => 'B_soldier_M_F',
      11 => 'B_soldier_LAT_F',
      12 => 'B_medic_F',
      13 => 'B_soldier_repair_F',
      14 => 'B_soldier_exp_F',
      15 => 'B_Helipilot_F',
      16 => 'B_diver_F',
      17 => 'B_diver_TL_F',
      18 => 'B_diver_exp_F',
      19 => 'B_spotter_F',
      20 => 'B_sniper_F',
      21 => 'B_RangeMaster_F',
      22 => 'O_Soldier_F',
      23 => 'O_officer_F',
      24 => 'O_Soldier_02_F',
      25 => 'O_Soldier_lite_F',
      26 => 'O_Soldier_GL_F',
      27 => 'O_Soldier_AR_F',
      28 => 'O_Soldier_SL_F',
      29 => 'O_Soldier_TL_F',
      30 => 'O_soldier_M_F',
      31 => 'O_Soldier_LAT_F',
      32 => 'O_medic_F',
      33 => 'O_soldier_repair_F',
      34 => 'O_soldier_exp_F',
      35 => 'O_helipilot_F',
      36 => 'O_diver_F',
      37 => 'O_diver_TL_F',
      38 => 'O_diver_exp_F',
      39 => 'O_spotter_F',
      40 => 'O_sniper_F',
      41 => 'B_Soldier_A_F',
      42 => 'B_soldier_AT_F',
      43 => 'B_soldier_AA_F',
      44 => 'B_engineer_F',
      45 => 'B_crew_F',
      46 => 'B_officer_F',
      47 => 'B_Competitor_F',
      48 => 'B_recon_F',
      49 => 'B_recon_LAT_F',
      50 => 'B_recon_exp_F',
      51 => 'B_recon_medic_F',
      52 => 'B_recon_TL_F',
      53 => 'B_recon_M_F',
      54 => 'B_recon_JTAC_F',
      55 => 'B_soldier_AAR_F',
      56 => 'B_soldier_AAT_F',
      57 => 'B_soldier_AAA_F',
      58 => 'O_Soldier_A_F',
      59 => 'O_Soldier_AT_F',
      60 => 'O_Soldier_AA_F',
      61 => 'O_engineer_F',
      62 => 'O_crew_F',
      63 => 'O_recon_F',
      64 => 'O_recon_M_F',
      65 => 'O_recon_LAT_F',
      66 => 'O_recon_medic_F',
      67 => 'O_recon_exp_F',
      68 => 'O_recon_JTAC_F',
      69 => 'O_recon_TL_F',
      70 => 'O_Soldier_AAR_F',
      71 => 'O_Soldier_AAT_F',
      72 => 'O_Soldier_AAA_F',
      73 => 'I_Soldier_02_F',
      74 => 'I_Soldier_03_F',
      75 => 'I_Soldier_04_F',
      76 => 'I_soldier_F',
      77 => 'I_Soldier_lite_F',
      78 => 'I_Soldier_A_F',
      79 => 'I_Soldier_GL_F',
      80 => 'I_Soldier_AR_F',
      81 => 'I_Soldier_SL_F',
      82 => 'I_Soldier_TL_F',
      83 => 'I_Soldier_M_F',
      84 => 'I_Soldier_LAT_F',
      85 => 'I_Soldier_AT_F',
      86 => 'I_Soldier_AA_F',
      87 => 'I_medic_F',
      88 => 'I_Soldier_repair_F',
      89 => 'I_Soldier_exp_F',
      90 => 'I_engineer_F',
      91 => 'I_crew_F',
      92 => 'I_helipilot_F',
      93 => 'I_helicrew_F',
      94 => 'I_officer_F',
      95 => 'I_Spotter_F',
      96 => 'I_Sniper_F',
      97 => 'I_diver_F',
      98 => 'I_diver_exp_F',
      99 => 'I_diver_TL_F',
      100 => 'I_Soldier_AAR_F',
      101 => 'I_Soldier_AAT_F',
      102 => 'I_Soldier_AAA_F',
      103 => 'B_Pilot_F',
      104 => 'B_helicrew_F',
      105 => 'B_soldier_PG_F',
      106 => 'B_Story_SF_Captain_F',
      107 => 'B_Story_Protagonist_F',
      108 => 'B_Story_Engineer_F',
      109 => 'B_Story_Colonel_F',
      110 => 'B_Story_Pilot_F',
      111 => 'B_Story_Tank_Commander_F',
      112 => 'B_support_MG_F',
      113 => 'B_support_GMG_F',
      114 => 'B_support_Mort_F',
      115 => 'B_support_AMG_F',
      116 => 'B_support_AMort_F',
      117 => 'I_pilot_F',
      118 => 'I_Story_Colonel_F',
      119 => 'I_support_MG_F',
      120 => 'I_support_GMG_F',
      121 => 'I_support_Mort_F',
      122 => 'I_support_AMG_F',
      123 => 'I_support_AMort_F',
      124 => 'O_Pilot_F',
      125 => 'O_helicrew_F',
      126 => 'O_soldier_PG_F',
      127 => 'O_Story_Colonel_F',
      128 => 'O_Story_CEO_F',
      129 => 'O_support_MG_F',
      130 => 'O_support_GMG_F',
      131 => 'O_support_Mort_F',
      132 => 'O_support_AMG_F',
      133 => 'O_support_AMort_F',
      134 => 'O_soldierU_F',
      135 => 'O_soldierU_AR_F',
      136 => 'O_soldierU_AAR_F',
      137 => 'O_soldierU_LAT_F',
      138 => 'O_soldierU_AT_F',
      139 => 'O_soldierU_AAT_F',
      140 => 'O_soldierU_AA_F',
      141 => 'O_soldierU_AAA_F',
      142 => 'O_soldierU_TL_F',
      143 => 'O_SoldierU_SL_F',
      144 => 'O_soldierU_medic_F',
      145 => 'O_soldierU_repair_F',
      146 => 'O_soldierU_exp_F',
      147 => 'O_engineer_U_F',
      148 => 'O_soldierU_M_F',
      149 => 'O_soldierU_A_F',
      150 => 'O_SoldierU_GL_F',
      151 => 'I_G_Soldier_F',
      152 => 'I_G_Soldier_lite_F',
      153 => 'I_G_Soldier_SL_F',
      154 => 'I_G_Soldier_TL_F',
      155 => 'I_G_Soldier_AR_F',
      156 => 'I_G_medic_F',
      157 => 'I_G_engineer_F',
      158 => 'I_G_Soldier_exp_F',
      159 => 'I_G_Soldier_GL_F',
      160 => 'I_G_Soldier_M_F',
      161 => 'I_G_Soldier_LAT_F',
      162 => 'I_G_Soldier_A_F',
      163 => 'I_G_officer_F',
      164 => 'B_G_Soldier_F',
      165 => 'O_G_Soldier_F',
      166 => 'B_G_Soldier_lite_F',
      167 => 'O_G_Soldier_lite_F',
      168 => 'B_G_Soldier_SL_F',
      169 => 'O_G_Soldier_SL_F',
      170 => 'B_G_Soldier_TL_F',
      171 => 'O_G_Soldier_TL_F',
      172 => 'B_G_Soldier_AR_F',
      173 => 'O_G_Soldier_AR_F',
      174 => 'B_G_medic_F',
      175 => 'O_G_medic_F',
      176 => 'B_G_engineer_F',
      177 => 'O_G_engineer_F',
      178 => 'B_G_Soldier_exp_F',
      179 => 'O_G_Soldier_exp_F',
      180 => 'B_G_Soldier_GL_F',
      181 => 'O_G_Soldier_GL_F',
      182 => 'B_G_Soldier_M_F',
      183 => 'O_G_Soldier_M_F',
      184 => 'B_G_Soldier_LAT_F',
      185 => 'O_G_Soldier_LAT_F',
      186 => 'B_G_Soldier_A_F',
      187 => 'O_G_Soldier_A_F',
      188 => 'B_G_officer_F',
      189 => 'O_G_officer_F',
      190 => 'I_G_Story_Protagonist_F',
      191 => 'B_soldier_UAV_F',
      192 => 'I_soldier_UAV_F',
      193 => 'O_soldier_UAV_F',
      194 => 'B_UAV_AI',
      195 => 'O_UAV_AI',
      196 => 'I_UAV_AI',
      197 => 'Underwear_F',
      198 => 'b_soldier_survival_F',
      199 => 'B_CTRG_soldier_GL_LAT_F',
      200 => 'B_CTRG_soldier_engineer_exp_F',
      201 => 'B_CTRG_soldier_M_medic_F',
      202 => 'B_CTRG_soldier_AR_A_F',
      203 => 'I_G_Story_SF_Captain_F',
      204 => 'I_G_resistanceLeader_F',
      205 => 'I_G_resistanceCommander_F',
      206 => 'b_soldier_unarmed_f',
      207 => 'b_g_soldier_unarmed_f',
      208 => 'o_soldier_unarmed_f',
      209 => 'o_g_soldier_unarmed_f',
      210 => 'i_soldier_unarmed_f',
      211 => 'i_g_soldier_unarmed_f',
      212 => 'VirtualMan_F',
      213 => 'VirtualCurator_F',
      214 => 'B_VirtualCurator_F',
      215 => 'O_VirtualCurator_F',
      216 => 'I_VirtualCurator_F',
      217 => 'C_VirtualCurator_F',
    ),
  ),
  4 => 
  array (
    'class' => 'ItemMap',
    'name' => 'Map',
    'description' => 'Enables viewing map.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_Soldier_F',
      1 => 'B_Soldier_02_f',
      2 => 'B_Soldier_03_f',
      3 => 'B_Soldier_04_f',
      4 => 'B_Soldier_05_f',
      5 => 'B_Soldier_lite_F',
      6 => 'B_Soldier_GL_F',
      7 => 'B_soldier_AR_F',
      8 => 'B_Soldier_SL_F',
      9 => 'B_Soldier_TL_F',
      10 => 'B_soldier_M_F',
      11 => 'B_soldier_LAT_F',
      12 => 'B_medic_F',
      13 => 'B_soldier_repair_F',
      14 => 'B_soldier_exp_F',
      15 => 'B_Helipilot_F',
      16 => 'B_diver_F',
      17 => 'B_diver_TL_F',
      18 => 'B_diver_exp_F',
      19 => 'B_spotter_F',
      20 => 'B_sniper_F',
      21 => 'B_RangeMaster_F',
      22 => 'C_man_1',
      23 => 'C_man_1_1_F',
      24 => 'C_man_1_2_F',
      25 => 'C_man_1_3_F',
      26 => 'C_man_polo_1_F',
      27 => 'C_man_polo_2_F',
      28 => 'C_man_polo_3_F',
      29 => 'C_man_polo_4_F',
      30 => 'C_man_polo_5_F',
      31 => 'C_man_polo_6_F',
      32 => 'C_Orestes',
      33 => 'C_Nikos',
      34 => 'O_Soldier_F',
      35 => 'O_officer_F',
      36 => 'O_Soldier_02_F',
      37 => 'O_Soldier_lite_F',
      38 => 'O_Soldier_GL_F',
      39 => 'O_Soldier_AR_F',
      40 => 'O_Soldier_SL_F',
      41 => 'O_Soldier_TL_F',
      42 => 'O_soldier_M_F',
      43 => 'O_Soldier_LAT_F',
      44 => 'O_medic_F',
      45 => 'O_soldier_repair_F',
      46 => 'O_soldier_exp_F',
      47 => 'O_helipilot_F',
      48 => 'O_diver_F',
      49 => 'O_diver_TL_F',
      50 => 'O_diver_exp_F',
      51 => 'O_spotter_F',
      52 => 'O_sniper_F',
      53 => 'B_Soldier_A_F',
      54 => 'B_soldier_AT_F',
      55 => 'B_soldier_AA_F',
      56 => 'B_engineer_F',
      57 => 'B_crew_F',
      58 => 'B_officer_F',
      59 => 'B_Competitor_F',
      60 => 'B_recon_F',
      61 => 'B_recon_LAT_F',
      62 => 'B_recon_exp_F',
      63 => 'B_recon_medic_F',
      64 => 'B_recon_TL_F',
      65 => 'B_recon_M_F',
      66 => 'B_recon_JTAC_F',
      67 => 'B_soldier_AAR_F',
      68 => 'B_soldier_AAT_F',
      69 => 'B_soldier_AAA_F',
      70 => 'O_Soldier_A_F',
      71 => 'O_Soldier_AT_F',
      72 => 'O_Soldier_AA_F',
      73 => 'O_engineer_F',
      74 => 'O_crew_F',
      75 => 'O_recon_F',
      76 => 'O_recon_M_F',
      77 => 'O_recon_LAT_F',
      78 => 'O_recon_medic_F',
      79 => 'O_recon_exp_F',
      80 => 'O_recon_JTAC_F',
      81 => 'O_recon_TL_F',
      82 => 'O_Soldier_AAR_F',
      83 => 'O_Soldier_AAT_F',
      84 => 'O_Soldier_AAA_F',
      85 => 'I_Soldier_02_F',
      86 => 'I_Soldier_03_F',
      87 => 'I_Soldier_04_F',
      88 => 'I_soldier_F',
      89 => 'I_Soldier_lite_F',
      90 => 'I_Soldier_A_F',
      91 => 'I_Soldier_GL_F',
      92 => 'I_Soldier_AR_F',
      93 => 'I_Soldier_SL_F',
      94 => 'I_Soldier_TL_F',
      95 => 'I_Soldier_M_F',
      96 => 'I_Soldier_LAT_F',
      97 => 'I_Soldier_AT_F',
      98 => 'I_Soldier_AA_F',
      99 => 'I_medic_F',
      100 => 'I_Soldier_repair_F',
      101 => 'I_Soldier_exp_F',
      102 => 'I_engineer_F',
      103 => 'I_crew_F',
      104 => 'I_helipilot_F',
      105 => 'I_helicrew_F',
      106 => 'I_officer_F',
      107 => 'I_Spotter_F',
      108 => 'I_Sniper_F',
      109 => 'I_diver_F',
      110 => 'I_diver_exp_F',
      111 => 'I_diver_TL_F',
      112 => 'I_Soldier_AAR_F',
      113 => 'I_Soldier_AAT_F',
      114 => 'I_Soldier_AAA_F',
      115 => 'B_Pilot_F',
      116 => 'B_helicrew_F',
      117 => 'B_soldier_PG_F',
      118 => 'B_Story_SF_Captain_F',
      119 => 'B_Story_Protagonist_F',
      120 => 'B_Story_Engineer_F',
      121 => 'B_Story_Colonel_F',
      122 => 'B_Story_Pilot_F',
      123 => 'B_Story_Tank_Commander_F',
      124 => 'B_support_MG_F',
      125 => 'B_support_GMG_F',
      126 => 'B_support_Mort_F',
      127 => 'B_support_AMG_F',
      128 => 'B_support_AMort_F',
      129 => 'I_pilot_F',
      130 => 'I_Story_Colonel_F',
      131 => 'I_support_MG_F',
      132 => 'I_support_GMG_F',
      133 => 'I_support_Mort_F',
      134 => 'I_support_AMG_F',
      135 => 'I_support_AMort_F',
      136 => 'O_Pilot_F',
      137 => 'O_helicrew_F',
      138 => 'O_soldier_PG_F',
      139 => 'O_Story_Colonel_F',
      140 => 'O_Story_CEO_F',
      141 => 'O_support_MG_F',
      142 => 'O_support_GMG_F',
      143 => 'O_support_Mort_F',
      144 => 'O_support_AMG_F',
      145 => 'O_support_AMort_F',
      146 => 'O_soldierU_F',
      147 => 'O_soldierU_AR_F',
      148 => 'O_soldierU_AAR_F',
      149 => 'O_soldierU_LAT_F',
      150 => 'O_soldierU_AT_F',
      151 => 'O_soldierU_AAT_F',
      152 => 'O_soldierU_AA_F',
      153 => 'O_soldierU_AAA_F',
      154 => 'O_soldierU_TL_F',
      155 => 'O_SoldierU_SL_F',
      156 => 'O_soldierU_medic_F',
      157 => 'O_soldierU_repair_F',
      158 => 'O_soldierU_exp_F',
      159 => 'O_engineer_U_F',
      160 => 'O_soldierU_M_F',
      161 => 'O_soldierU_A_F',
      162 => 'O_SoldierU_GL_F',
      163 => 'C_man_p_fugitive_F',
      164 => 'C_man_p_fugitive_F_afro',
      165 => 'C_man_p_fugitive_F_euro',
      166 => 'C_man_p_fugitive_F_asia',
      167 => 'C_man_p_beggar_F',
      168 => 'C_man_p_beggar_F_afro',
      169 => 'C_man_p_beggar_F_euro',
      170 => 'C_man_p_beggar_F_asia',
      171 => 'C_man_w_worker_F',
      172 => 'C_man_hunter_1_F',
      173 => 'C_man_p_shorts_1_F',
      174 => 'C_man_p_shorts_1_F_afro',
      175 => 'C_man_p_shorts_1_F_euro',
      176 => 'C_man_p_shorts_1_F_asia',
      177 => 'C_man_shorts_1_F',
      178 => 'C_man_shorts_1_F_afro',
      179 => 'C_man_shorts_1_F_euro',
      180 => 'C_man_shorts_1_F_asia',
      181 => 'C_man_shorts_2_F',
      182 => 'C_man_shorts_2_F_afro',
      183 => 'C_man_shorts_2_F_euro',
      184 => 'C_man_shorts_2_F_asia',
      185 => 'C_man_shorts_3_F',
      186 => 'C_man_shorts_3_F_afro',
      187 => 'C_man_shorts_3_F_euro',
      188 => 'C_man_shorts_3_F_asia',
      189 => 'C_man_shorts_4_F',
      190 => 'C_man_shorts_4_F_afro',
      191 => 'C_man_shorts_4_F_euro',
      192 => 'C_man_shorts_4_F_asia',
      193 => 'C_man_pilot_F',
      194 => 'C_man_polo_1_F_afro',
      195 => 'C_man_polo_1_F_euro',
      196 => 'C_man_polo_1_F_asia',
      197 => 'C_man_polo_2_F_afro',
      198 => 'C_man_polo_2_F_euro',
      199 => 'C_man_polo_2_F_asia',
      200 => 'C_man_polo_3_F_afro',
      201 => 'C_man_polo_3_F_euro',
      202 => 'C_man_polo_3_F_asia',
      203 => 'C_man_polo_4_F_afro',
      204 => 'C_man_polo_4_F_euro',
      205 => 'C_man_polo_4_F_asia',
      206 => 'C_man_polo_5_F_afro',
      207 => 'C_man_polo_5_F_euro',
      208 => 'C_man_polo_5_F_asia',
      209 => 'C_man_polo_6_F_afro',
      210 => 'C_man_polo_6_F_euro',
      211 => 'C_man_polo_6_F_asia',
      212 => 'I_G_Soldier_F',
      213 => 'I_G_Soldier_lite_F',
      214 => 'I_G_Soldier_SL_F',
      215 => 'I_G_Soldier_TL_F',
      216 => 'I_G_Soldier_AR_F',
      217 => 'I_G_medic_F',
      218 => 'I_G_engineer_F',
      219 => 'I_G_Soldier_exp_F',
      220 => 'I_G_Soldier_GL_F',
      221 => 'I_G_Soldier_M_F',
      222 => 'I_G_Soldier_LAT_F',
      223 => 'I_G_Soldier_A_F',
      224 => 'I_G_officer_F',
      225 => 'B_G_Soldier_F',
      226 => 'O_G_Soldier_F',
      227 => 'B_G_Soldier_lite_F',
      228 => 'O_G_Soldier_lite_F',
      229 => 'B_G_Soldier_SL_F',
      230 => 'O_G_Soldier_SL_F',
      231 => 'B_G_Soldier_TL_F',
      232 => 'O_G_Soldier_TL_F',
      233 => 'B_G_Soldier_AR_F',
      234 => 'O_G_Soldier_AR_F',
      235 => 'B_G_medic_F',
      236 => 'O_G_medic_F',
      237 => 'B_G_engineer_F',
      238 => 'O_G_engineer_F',
      239 => 'B_G_Soldier_exp_F',
      240 => 'O_G_Soldier_exp_F',
      241 => 'B_G_Soldier_GL_F',
      242 => 'O_G_Soldier_GL_F',
      243 => 'B_G_Soldier_M_F',
      244 => 'O_G_Soldier_M_F',
      245 => 'B_G_Soldier_LAT_F',
      246 => 'O_G_Soldier_LAT_F',
      247 => 'B_G_Soldier_A_F',
      248 => 'O_G_Soldier_A_F',
      249 => 'B_G_officer_F',
      250 => 'O_G_officer_F',
      251 => 'I_G_Story_Protagonist_F',
      252 => 'B_soldier_UAV_F',
      253 => 'I_soldier_UAV_F',
      254 => 'O_soldier_UAV_F',
      255 => 'B_UAV_AI',
      256 => 'O_UAV_AI',
      257 => 'I_UAV_AI',
      258 => 'Underwear_F',
      259 => 'b_soldier_survival_F',
      260 => 'B_CTRG_soldier_GL_LAT_F',
      261 => 'B_CTRG_soldier_engineer_exp_F',
      262 => 'B_CTRG_soldier_M_medic_F',
      263 => 'B_CTRG_soldier_AR_A_F',
      264 => 'I_G_Story_SF_Captain_F',
      265 => 'I_G_resistanceLeader_F',
      266 => 'I_G_resistanceCommander_F',
      267 => 'C_Nikos_aged',
      268 => 'C_journalist_F',
      269 => 'C_scientist_F',
      270 => 'b_soldier_unarmed_f',
      271 => 'b_g_soldier_unarmed_f',
      272 => 'o_soldier_unarmed_f',
      273 => 'o_g_soldier_unarmed_f',
      274 => 'i_soldier_unarmed_f',
      275 => 'i_g_soldier_unarmed_f',
      276 => 'VirtualMan_F',
      277 => 'VirtualCurator_F',
      278 => 'B_VirtualCurator_F',
      279 => 'O_VirtualCurator_F',
      280 => 'I_VirtualCurator_F',
      281 => 'C_VirtualCurator_F',
    ),
  ),
  5 => 
  array (
    'class' => 'MineDetector',
    'name' => 'Mine Detector',
    'description' => 'Detects all mines in range.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  6 => 
  array (
    'class' => 'Binocular',
    'name' => 'Binoculars',
    'description' => 'Binoculars allow the soldier to survey the battlefield over long distances.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_Soldier_SL_F',
      1 => 'O_Soldier_SL_F',
      2 => 'O_diver_TL_F',
      3 => 'B_recon_F',
      4 => 'O_recon_F',
      5 => 'I_Soldier_SL_F',
      6 => 'O_SoldierU_SL_F',
      7 => 'I_G_Soldier_SL_F',
      8 => 'B_G_Soldier_SL_F',
      9 => 'O_G_Soldier_SL_F',
    ),
  ),
  7 => 
  array (
    'class' => 'Rangefinder',
    'name' => 'Rangefinder',
    'description' => 'Rangefinder<br />Magnification: 3xâ€“60x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_sniper_F',
      1 => 'O_sniper_F',
      2 => 'B_recon_TL_F',
      3 => 'B_soldier_AAR_F',
      4 => 'B_soldier_AAT_F',
      5 => 'B_soldier_AAA_F',
      6 => 'O_recon_M_F',
      7 => 'O_recon_TL_F',
      8 => 'O_Soldier_AAR_F',
      9 => 'O_Soldier_AAT_F',
      10 => 'O_Soldier_AAA_F',
      11 => 'I_Sniper_F',
      12 => 'I_Soldier_AAR_F',
      13 => 'I_Soldier_AAT_F',
      14 => 'I_Soldier_AAA_F',
      15 => 'O_soldierU_M_F',
    ),
  ),
  8 => 
  array (
    'class' => 'NVGoggles',
    'name' => 'NV Goggles (Brown)',
    'description' => 'Night Vision Goggles',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_Soldier_F',
      1 => 'B_Soldier_02_f',
      2 => 'B_Soldier_03_f',
      3 => 'B_Soldier_04_f',
      4 => 'B_Soldier_05_f',
      5 => 'B_Soldier_lite_F',
      6 => 'B_Soldier_GL_F',
      7 => 'B_soldier_AR_F',
      8 => 'B_Soldier_SL_F',
      9 => 'B_Soldier_TL_F',
      10 => 'B_soldier_M_F',
      11 => 'B_soldier_LAT_F',
      12 => 'B_medic_F',
      13 => 'B_soldier_repair_F',
      14 => 'B_soldier_exp_F',
      15 => 'B_Helipilot_F',
      16 => 'B_spotter_F',
      17 => 'B_sniper_F',
      18 => 'B_Soldier_A_F',
      19 => 'B_soldier_AT_F',
      20 => 'B_soldier_AA_F',
      21 => 'B_engineer_F',
      22 => 'B_crew_F',
      23 => 'B_recon_F',
      24 => 'B_recon_LAT_F',
      25 => 'B_recon_exp_F',
      26 => 'B_recon_medic_F',
      27 => 'B_recon_TL_F',
      28 => 'B_recon_M_F',
      29 => 'B_recon_JTAC_F',
      30 => 'B_soldier_AAR_F',
      31 => 'B_soldier_AAT_F',
      32 => 'B_soldier_AAA_F',
      33 => 'B_helicrew_F',
      34 => 'B_soldier_PG_F',
      35 => 'B_Story_Protagonist_F',
      36 => 'B_Story_Engineer_F',
      37 => 'B_Story_Colonel_F',
      38 => 'B_Story_Pilot_F',
      39 => 'B_Story_Tank_Commander_F',
      40 => 'B_support_MG_F',
      41 => 'B_support_GMG_F',
      42 => 'B_support_Mort_F',
      43 => 'B_support_AMG_F',
      44 => 'B_support_AMort_F',
      45 => 'B_soldier_UAV_F',
      46 => 'B_UAV_AI',
      47 => 'Underwear_F',
      48 => 'b_soldier_survival_F',
      49 => 'B_CTRG_soldier_GL_LAT_F',
      50 => 'B_CTRG_soldier_engineer_exp_F',
      51 => 'B_CTRG_soldier_M_medic_F',
      52 => 'B_CTRG_soldier_AR_A_F',
    ),
  ),
  9 => 
  array (
    'class' => 'NVGoggles_OPFOR',
    'name' => 'NV Goggles (Black)',
    'description' => 'Night Vision Goggles',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'O_Soldier_F',
      1 => 'O_Soldier_02_F',
      2 => 'O_Soldier_lite_F',
      3 => 'O_Soldier_GL_F',
      4 => 'O_Soldier_AR_F',
      5 => 'O_Soldier_SL_F',
      6 => 'O_Soldier_TL_F',
      7 => 'O_soldier_M_F',
      8 => 'O_Soldier_LAT_F',
      9 => 'O_medic_F',
      10 => 'O_soldier_repair_F',
      11 => 'O_soldier_exp_F',
      12 => 'O_helipilot_F',
      13 => 'O_spotter_F',
      14 => 'O_sniper_F',
      15 => 'O_Soldier_A_F',
      16 => 'O_Soldier_AT_F',
      17 => 'O_Soldier_AA_F',
      18 => 'O_engineer_F',
      19 => 'O_crew_F',
      20 => 'O_recon_F',
      21 => 'O_recon_M_F',
      22 => 'O_recon_LAT_F',
      23 => 'O_recon_medic_F',
      24 => 'O_recon_exp_F',
      25 => 'O_recon_JTAC_F',
      26 => 'O_recon_TL_F',
      27 => 'O_Soldier_AAR_F',
      28 => 'O_Soldier_AAT_F',
      29 => 'O_Soldier_AAA_F',
      30 => 'O_helicrew_F',
      31 => 'O_soldier_PG_F',
      32 => 'O_Story_Colonel_F',
      33 => 'O_Story_CEO_F',
      34 => 'O_support_MG_F',
      35 => 'O_support_GMG_F',
      36 => 'O_support_Mort_F',
      37 => 'O_support_AMG_F',
      38 => 'O_support_AMort_F',
      39 => 'O_soldierU_F',
      40 => 'O_soldierU_AR_F',
      41 => 'O_soldierU_AAR_F',
      42 => 'O_soldierU_LAT_F',
      43 => 'O_soldierU_AT_F',
      44 => 'O_soldierU_AAT_F',
      45 => 'O_soldierU_AA_F',
      46 => 'O_soldierU_AAA_F',
      47 => 'O_soldierU_TL_F',
      48 => 'O_SoldierU_SL_F',
      49 => 'O_soldierU_medic_F',
      50 => 'O_soldierU_repair_F',
      51 => 'O_soldierU_exp_F',
      52 => 'O_engineer_U_F',
      53 => 'O_soldierU_M_F',
      54 => 'O_soldierU_A_F',
      55 => 'O_SoldierU_GL_F',
      56 => 'O_soldier_UAV_F',
      57 => 'O_UAV_AI',
      58 => 'I_UAV_AI',
    ),
  ),
  10 => 
  array (
    'class' => 'NVGoggles_INDEP',
    'name' => 'NV Goggles (Green)',
    'description' => 'Night Vision Goggles',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'I_Soldier_02_F',
      1 => 'I_Soldier_03_F',
      2 => 'I_Soldier_04_F',
      3 => 'I_soldier_F',
      4 => 'I_Soldier_lite_F',
      5 => 'I_Soldier_A_F',
      6 => 'I_Soldier_GL_F',
      7 => 'I_Soldier_AR_F',
      8 => 'I_Soldier_SL_F',
      9 => 'I_Soldier_TL_F',
      10 => 'I_Soldier_M_F',
      11 => 'I_Soldier_LAT_F',
      12 => 'I_Soldier_AT_F',
      13 => 'I_Soldier_AA_F',
      14 => 'I_medic_F',
      15 => 'I_Soldier_repair_F',
      16 => 'I_Soldier_exp_F',
      17 => 'I_engineer_F',
      18 => 'I_crew_F',
      19 => 'I_helipilot_F',
      20 => 'I_helicrew_F',
      21 => 'I_Spotter_F',
      22 => 'I_Sniper_F',
      23 => 'I_Soldier_AAR_F',
      24 => 'I_Soldier_AAT_F',
      25 => 'I_Soldier_AAA_F',
      26 => 'I_support_MG_F',
      27 => 'I_support_GMG_F',
      28 => 'I_support_Mort_F',
      29 => 'I_support_AMG_F',
      30 => 'I_support_AMort_F',
      31 => 'I_soldier_UAV_F',
    ),
  ),
  11 => 
  array (
    'class' => 'FirstAidKit',
    'name' => 'First Aid Kit',
    'description' => 'Use to treat heavy wounds.<br />Usable on: Self, Others',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_Soldier_F',
      1 => 'B_Soldier_02_f',
      2 => 'B_Soldier_03_f',
      3 => 'B_Soldier_04_f',
      4 => 'B_Soldier_05_f',
      5 => 'B_Soldier_lite_F',
      6 => 'B_Soldier_GL_F',
      7 => 'B_soldier_AR_F',
      8 => 'B_Soldier_SL_F',
      9 => 'B_Soldier_TL_F',
      10 => 'B_soldier_M_F',
      11 => 'B_soldier_LAT_F',
      12 => 'B_medic_F',
      13 => 'B_soldier_repair_F',
      14 => 'B_soldier_exp_F',
      15 => 'B_Helipilot_F',
      16 => 'B_diver_F',
      17 => 'B_diver_TL_F',
      18 => 'B_diver_exp_F',
      19 => 'B_spotter_F',
      20 => 'B_sniper_F',
      21 => 'B_RangeMaster_F',
      22 => 'O_Soldier_F',
      23 => 'O_officer_F',
      24 => 'O_Soldier_02_F',
      25 => 'O_Soldier_lite_F',
      26 => 'O_Soldier_GL_F',
      27 => 'O_Soldier_AR_F',
      28 => 'O_Soldier_SL_F',
      29 => 'O_Soldier_TL_F',
      30 => 'O_soldier_M_F',
      31 => 'O_Soldier_LAT_F',
      32 => 'O_medic_F',
      33 => 'O_soldier_repair_F',
      34 => 'O_soldier_exp_F',
      35 => 'O_helipilot_F',
      36 => 'O_diver_F',
      37 => 'O_diver_TL_F',
      38 => 'O_diver_exp_F',
      39 => 'O_spotter_F',
      40 => 'O_sniper_F',
      41 => 'B_Soldier_A_F',
      42 => 'B_soldier_AT_F',
      43 => 'B_soldier_AA_F',
      44 => 'B_engineer_F',
      45 => 'B_crew_F',
      46 => 'B_officer_F',
      47 => 'B_Competitor_F',
      48 => 'B_recon_F',
      49 => 'B_recon_LAT_F',
      50 => 'B_recon_exp_F',
      51 => 'B_recon_medic_F',
      52 => 'B_recon_TL_F',
      53 => 'B_recon_M_F',
      54 => 'B_recon_JTAC_F',
      55 => 'B_soldier_AAR_F',
      56 => 'B_soldier_AAT_F',
      57 => 'B_soldier_AAA_F',
      58 => 'O_Soldier_A_F',
      59 => 'O_Soldier_AT_F',
      60 => 'O_Soldier_AA_F',
      61 => 'O_engineer_F',
      62 => 'O_crew_F',
      63 => 'O_recon_F',
      64 => 'O_recon_M_F',
      65 => 'O_recon_LAT_F',
      66 => 'O_recon_medic_F',
      67 => 'O_recon_exp_F',
      68 => 'O_recon_JTAC_F',
      69 => 'O_recon_TL_F',
      70 => 'O_Soldier_AAR_F',
      71 => 'O_Soldier_AAT_F',
      72 => 'O_Soldier_AAA_F',
      73 => 'I_Soldier_02_F',
      74 => 'I_Soldier_03_F',
      75 => 'I_Soldier_04_F',
      76 => 'I_soldier_F',
      77 => 'I_Soldier_lite_F',
      78 => 'I_Soldier_A_F',
      79 => 'I_Soldier_GL_F',
      80 => 'I_Soldier_AR_F',
      81 => 'I_Soldier_SL_F',
      82 => 'I_Soldier_TL_F',
      83 => 'I_Soldier_M_F',
      84 => 'I_Soldier_LAT_F',
      85 => 'I_Soldier_AT_F',
      86 => 'I_Soldier_AA_F',
      87 => 'I_medic_F',
      88 => 'I_Soldier_repair_F',
      89 => 'I_Soldier_exp_F',
      90 => 'I_engineer_F',
      91 => 'I_crew_F',
      92 => 'I_helipilot_F',
      93 => 'I_helicrew_F',
      94 => 'I_officer_F',
      95 => 'I_Spotter_F',
      96 => 'I_Sniper_F',
      97 => 'I_diver_F',
      98 => 'I_diver_exp_F',
      99 => 'I_diver_TL_F',
      100 => 'I_Soldier_AAR_F',
      101 => 'I_Soldier_AAT_F',
      102 => 'I_Soldier_AAA_F',
      103 => 'B_Pilot_F',
      104 => 'B_helicrew_F',
      105 => 'B_soldier_PG_F',
      106 => 'B_Story_SF_Captain_F',
      107 => 'B_Story_Protagonist_F',
      108 => 'B_Story_Engineer_F',
      109 => 'B_Story_Colonel_F',
      110 => 'B_Story_Pilot_F',
      111 => 'B_Story_Tank_Commander_F',
      112 => 'B_support_MG_F',
      113 => 'B_support_GMG_F',
      114 => 'B_support_Mort_F',
      115 => 'B_support_AMG_F',
      116 => 'B_support_AMort_F',
      117 => 'I_pilot_F',
      118 => 'I_Story_Colonel_F',
      119 => 'I_support_MG_F',
      120 => 'I_support_GMG_F',
      121 => 'I_support_Mort_F',
      122 => 'I_support_AMG_F',
      123 => 'I_support_AMort_F',
      124 => 'O_Pilot_F',
      125 => 'O_helicrew_F',
      126 => 'O_soldier_PG_F',
      127 => 'O_Story_Colonel_F',
      128 => 'O_Story_CEO_F',
      129 => 'O_support_MG_F',
      130 => 'O_support_GMG_F',
      131 => 'O_support_Mort_F',
      132 => 'O_support_AMG_F',
      133 => 'O_support_AMort_F',
      134 => 'O_soldierU_F',
      135 => 'O_soldierU_AR_F',
      136 => 'O_soldierU_AAR_F',
      137 => 'O_soldierU_LAT_F',
      138 => 'O_soldierU_AT_F',
      139 => 'O_soldierU_AAT_F',
      140 => 'O_soldierU_AA_F',
      141 => 'O_soldierU_AAA_F',
      142 => 'O_soldierU_TL_F',
      143 => 'O_SoldierU_SL_F',
      144 => 'O_soldierU_medic_F',
      145 => 'O_soldierU_repair_F',
      146 => 'O_soldierU_exp_F',
      147 => 'O_engineer_U_F',
      148 => 'O_soldierU_M_F',
      149 => 'O_soldierU_A_F',
      150 => 'O_SoldierU_GL_F',
      151 => 'I_G_Soldier_F',
      152 => 'I_G_Soldier_lite_F',
      153 => 'I_G_Soldier_SL_F',
      154 => 'I_G_Soldier_TL_F',
      155 => 'I_G_Soldier_AR_F',
      156 => 'I_G_medic_F',
      157 => 'I_G_engineer_F',
      158 => 'I_G_Soldier_exp_F',
      159 => 'I_G_Soldier_GL_F',
      160 => 'I_G_Soldier_M_F',
      161 => 'I_G_Soldier_LAT_F',
      162 => 'I_G_Soldier_A_F',
      163 => 'I_G_officer_F',
      164 => 'B_G_Soldier_F',
      165 => 'O_G_Soldier_F',
      166 => 'B_G_Soldier_lite_F',
      167 => 'O_G_Soldier_lite_F',
      168 => 'B_G_Soldier_SL_F',
      169 => 'O_G_Soldier_SL_F',
      170 => 'B_G_Soldier_TL_F',
      171 => 'O_G_Soldier_TL_F',
      172 => 'B_G_Soldier_AR_F',
      173 => 'O_G_Soldier_AR_F',
      174 => 'B_G_medic_F',
      175 => 'O_G_medic_F',
      176 => 'B_G_engineer_F',
      177 => 'O_G_engineer_F',
      178 => 'B_G_Soldier_exp_F',
      179 => 'O_G_Soldier_exp_F',
      180 => 'B_G_Soldier_GL_F',
      181 => 'O_G_Soldier_GL_F',
      182 => 'B_G_Soldier_M_F',
      183 => 'O_G_Soldier_M_F',
      184 => 'B_G_Soldier_LAT_F',
      185 => 'O_G_Soldier_LAT_F',
      186 => 'B_G_Soldier_A_F',
      187 => 'O_G_Soldier_A_F',
      188 => 'B_G_officer_F',
      189 => 'O_G_officer_F',
      190 => 'I_G_Story_Protagonist_F',
      191 => 'B_soldier_UAV_F',
      192 => 'I_soldier_UAV_F',
      193 => 'O_soldier_UAV_F',
      194 => 'B_UAV_AI',
      195 => 'O_UAV_AI',
      196 => 'I_UAV_AI',
      197 => 'Underwear_F',
      198 => 'b_soldier_survival_F',
      199 => 'B_CTRG_soldier_GL_LAT_F',
      200 => 'B_CTRG_soldier_engineer_exp_F',
      201 => 'B_CTRG_soldier_M_medic_F',
      202 => 'B_CTRG_soldier_AR_A_F',
      203 => 'I_G_Story_SF_Captain_F',
      204 => 'I_G_resistanceLeader_F',
      205 => 'I_G_resistanceCommander_F',
      206 => 'b_soldier_unarmed_f',
      207 => 'b_g_soldier_unarmed_f',
      208 => 'o_soldier_unarmed_f',
      209 => 'o_g_soldier_unarmed_f',
      210 => 'i_soldier_unarmed_f',
      211 => 'i_g_soldier_unarmed_f',
    ),
  ),
  12 => 
  array (
    'class' => 'Medikit',
    'name' => 'Medikit',
    'description' => 'Enables the treatment of any wounds.<br />Unlimited number of uses<br />Used by: Medic',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  13 => 
  array (
    'class' => 'ToolKit',
    'name' => 'Toolkit',
    'description' => 'Enables repair of vehicles - Engineer<br />Enables disarming of explosives - Demo expert',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  14 => 
  array (
    'class' => 'Laserdesignator',
    'name' => 'Laser Designator',
    'description' => 'Laser Designator',
    'magazines' => 
    array (
      0 => 'Laserbatteries',
    ),
    'usedby' => 
    array (
      0 => 'B_spotter_F',
      1 => 'O_spotter_F',
      2 => 'B_recon_M_F',
      3 => 'B_recon_JTAC_F',
      4 => 'O_recon_JTAC_F',
      5 => 'I_Spotter_F',
    ),
  ),
  15 => 
  array (
    'class' => 'B_UavTerminal',
    'name' => 'UAV Terminal',
    'description' => 'Use this Terminal to connect to UAVs.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'B_soldier_UAV_F',
    ),
  ),
  16 => 
  array (
    'class' => 'O_UavTerminal',
    'name' => 'UAV Terminal',
    'description' => 'Use this Terminal to connect to UAVs.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'O_soldier_UAV_F',
    ),
  ),
  17 => 
  array (
    'class' => 'I_UavTerminal',
    'name' => 'UAV Terminal',
    'description' => 'Use this Terminal to connect to UAVs.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
      0 => 'I_soldier_UAV_F',
    ),
  ),
  18 => 
  array (
    'class' => 'Zasleh2',
    'name' => NULL,
    'description' => NULL,
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  19 => 
  array (
    'class' => 'muzzle_snds_H',
    'name' => 'Sound Suppressor (6.5 mm)',
    'description' => NULL,
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  20 => 
  array (
    'class' => 'muzzle_snds_L',
    'name' => 'Sound Suppressor (9 mm)',
    'description' => NULL,
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  21 => 
  array (
    'class' => 'muzzle_snds_M',
    'name' => 'Sound Suppressor (5.56 mm)',
    'description' => NULL,
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  22 => 
  array (
    'class' => 'muzzle_snds_B',
    'name' => 'Sound Suppressor (7.62 mm)',
    'description' => NULL,
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  23 => 
  array (
    'class' => 'muzzle_snds_H_MG',
    'name' => 'Sound Suppressor LMG (6.5 mm)',
    'description' => NULL,
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  24 => 
  array (
    'class' => 'optic_Arco',
    'name' => 'ARCO',
    'description' => 'Advanced Rifle Combat Optics<br />Magnification: 10x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  25 => 
  array (
    'class' => 'optic_Hamr',
    'name' => 'RCO',
    'description' => 'Rifle Combat Optics<br />Magnification: 10x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  26 => 
  array (
    'class' => 'optic_Aco',
    'name' => 'ACO (Red)',
    'description' => 'Advanced Collimator Optics<br />Color: Red',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  27 => 
  array (
    'class' => 'optic_ACO_grn',
    'name' => 'ACO (Green)',
    'description' => 'Advanced Collimator Optics<br />Color: Green',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  28 => 
  array (
    'class' => 'optic_Aco_smg',
    'name' => 'ACO SMG (Red)',
    'description' => 'Advanced Collimator Optics<br />Color: Red',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  29 => 
  array (
    'class' => 'optic_ACO_grn_smg',
    'name' => 'ACO SMG (Green)',
    'description' => 'Advanced Collimator Optics<br />Color: Green',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  30 => 
  array (
    'class' => 'optic_Holosight',
    'name' => 'MK17 Holosight',
    'description' => 'Mk17 Holosight<br />Magnification: 1xâ€“2x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  31 => 
  array (
    'class' => 'optic_Holosight_smg',
    'name' => 'Mk17 Holosight SMG',
    'description' => 'Mk17 Holosight<br />Magnification: 1xâ€“2x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  32 => 
  array (
    'class' => 'optic_SOS',
    'name' => 'SOS',
    'description' => 'Sniper Optical Sights<br />Magnification: 18xâ€“75x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  33 => 
  array (
    'class' => 'acc_flashlight',
    'name' => 'Flashlight',
    'description' => 'Weapon mounted light.',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  34 => 
  array (
    'class' => 'acc_pointer_IR',
    'name' => 'IR Laser Pointer',
    'description' => 'Emits light visible in the image intensification mode (night vision).',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  35 => 
  array (
    'class' => 'optic_MRCO',
    'name' => 'MRCO',
    'description' => 'MRCO<br />Magnification: 1xâ€“6x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  36 => 
  array (
    'class' => 'muzzle_snds_acp',
    'name' => 'Sound Suppressor (.45 ACP)',
    'description' => NULL,
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  37 => 
  array (
    'class' => 'optic_DMS',
    'name' => 'DMS',
    'description' => 'DMS<br />Magnification: 1xâ€“12x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  38 => 
  array (
    'class' => 'optic_Yorris',
    'name' => 'Yorris J2',
    'description' => 'Y-J2<br />Magnification: 1x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  39 => 
  array (
    'class' => 'optic_MRD',
    'name' => 'MRD',
    'description' => 'MRD<br />Magnification: 1x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  40 => 
  array (
    'class' => 'optic_LRPS',
    'name' => 'LRPS',
    'description' => 'Long-Range Precision Scope<br />Magnification: 18xâ€“75x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  41 => 
  array (
    'class' => 'optic_NVS',
    'name' => 'NVS',
    'description' => 'Night Vision Scope<br />Magnification: 10x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  42 => 
  array (
    'class' => 'optic_Nightstalker',
    'name' => 'Nightstalker',
    'description' => 'Nightstalker Sight<br />Magnification: 5xâ€“25x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  43 => 
  array (
    'class' => 'optic_tws',
    'name' => 'TWS',
    'description' => 'Thermal Weapon Sight<br />Magnification: 10xâ€“23x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
  44 => 
  array (
    'class' => 'optic_tws_mg',
    'name' => 'TWS MG',
    'description' => 'Thermal Weapon Sight for Machineguns<br />Magnification: 12xâ€“27x',
    'magazines' => 
    array (
    ),
    'usedby' => 
    array (
    ),
  ),
);